---
name: "ListenBrainz"
guid: "59B20823-AAFE-454C-A393-17427F518631"
version: "5.1.2.1"
targetAbi: "10.10.0.0"
framework: "net8.0"
overview: "Track your music habits with ListenBrainz."
description: >
  A plugin to send your music listening activity on Jellyfin to ListenBrainz.
category: "General"
owner: "lyarenei"
artifacts:
  - "Jellyfin.Plugin.ListenBrainz.dll"
  - "Jellyfin.Plugin.ListenBrainz.Api.dll"
  - "Jellyfin.Plugin.ListenBrainz.Common.dll"
  - "Jellyfin.Plugin.ListenBrainz.Http.dll"
  - "Jellyfin.Plugin.ListenBrainz.MusicBrainzApi.dll"
changelog: >
  Fix
    - Issue with server crashing (#122 @lyarenei)

  If you have installed previous version (5.1.1.3) and experiencing server crash,
  you will need to manually remove the plugin version and install this one.
