---
name: "ListenBrainz"
guid: "59B20823-AAFE-454C-A393-17427F518631"
version: "5.3.0.1"
targetAbi: "10.10.0.0"
framework: "net8.0"
overview: "Track your music habits with ListenBrainz."
description: >
  A plugin to send your music listening activity on Jellyfin to ListenBrainz.
category: "General"
owner: "lyarenei"
artifacts:
  - "Jellyfin.Plugin.ListenBrainz.dll"
  - "Jellyfin.Plugin.ListenBrainz.Api.dll"
  - "Jellyfin.Plugin.ListenBrainz.Common.dll"
  - "Jellyfin.Plugin.ListenBrainz.Http.dll"
  - "Jellyfin.Plugin.ListenBrainz.MusicBrainzApi.dll"
changelog: >
  Maintenance:
    - Plugin code cleanup (backport from version 6.0.3.7)
    - Fix duplication of items in plugin config (backport from version 6.0.3.7)
    - Fix plugin settings error for mixed type libraries (backport from version 6.0.4.0)
  New:
    - New strict mode option for ListenBrainz submissions (backport from version 6.1.0.1)
