# $schema: https://json.schemastore.org/github-workflow
name: 'Publish Plugin'

on:
  workflow_call:
    inputs:
      repo:
        type: string
        required: true
    secrets:
      host:
        required: true
      user:
        required: true
      key:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      MANIFEST_FILE: "/var/www/repos/${{ inputs.repo }}/manifest.json"
      REPO_PATH: "/var/www/repos/${{ inputs.repo }}"
      REPO_URL: "https://repo.xkrivo.net/${{ inputs.repo }}"
    steps:
      - name: Update Plugin Manifest
        uses: appleboy/ssh-action@029f5b4aeeeb58fdfe1410a5d17f967dacf36262 # v1.0.3
        with:
          host: ${{ secrets.host }}
          username: ${{ secrets.user }}
          key: ${{ secrets.key }}
          script_stop: true
          envs: MANIFEST_FILE,REPO_PATH,REPO_URL
          script: |-
            lockfile="/run/lock/jprm.lock"
            pushd "${REPO_PATH}/${{ github.repository }}/${{ inputs.version }}" || exit 1
            (
                flock -x 300
                python3.9 -m jprm --verbosity=debug repo add --url="${REPO_URL}" "${MANIFEST_FILE}" ./*.zip || exit 1
            ) 300>${lockfile}
            popd || exit 1
            rm -r "${REPO_PATH}/${{ github.repository }}/${{ inputs.version }}" || exit 1
